spring:
  datasource:
    url: jdbc:mysql://${MY_COWS_HOST:localhost}:3306/my_cows_db?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASS:toor}

mycows:
  environment: DEV